
# Introduction to Data Analytics Libraries

Data analytics involves analyzing raw data to find trends and answer questions. The Python ecosystem has robust libraries for data analytics; Numpy, Pandas, and Seaborn are foundational tools that enable efficient data analysis and visualization.

## Numpy
Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Pandas
Pandas is an open-source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

## Seaborn
Seaborn is a Python visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.



## Getting Started with Numpy

Numpy is the core library for numerical computations in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.


### Basic Numpy Arrays
```python
import numpy as np

a = np.array([1, 2, 3])
print(a)
```

In [ ]:
#import statement

In [ ]:
# for new installation you us
#pip install numpy

In [55]:
import numpy

In [24]:
#np as the alias because of convention
import numpy as np

In [19]:
# single dimension array
arr1 = np.array([1,3,5,7,4,6])

In [20]:
type(arr1)

numpy.ndarray

In [21]:
arr1

array([1, 3, 5, 7, 4, 6])

In [22]:
#2d array
np.array([[1,3,5,7],[2,5,7,8]])

array([[1, 3, 5, 7],
       [2, 5, 7, 8]])

In [23]:
#2d array
np.array([[1,3,5,7],[2,5,7,8]], dtype=float)

array([[1., 3., 5., 7.],
       [2., 5., 7., 8.]])

In [32]:
dim = np.array([[1,3,5,7],[2,5,7,8]], dtype=float)

In [34]:
# shape or dimension
dim.shape

# 2 rows, 4 columns

(2, 4)

### Operations with Numpy Arrays
Numpy arrays support various operations, which are performed element-wise.
```python
b = np.array([4, 5, 6])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)
```

In [25]:
arr1

array([1, 3, 5, 7, 4, 6])

In [26]:
list2 = [3, 5, 6, 8, 10, 15]

In [27]:
arr2 = np.array(list2)

In [28]:
arr2

array([ 3,  5,  6,  8, 10, 15])

In [29]:
arr1 + arr2

array([ 4,  8, 11, 15, 14, 21])

In [30]:
# no element-wise with different shape

arr3 = np.array([2,4,6])

In [31]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [35]:
#broadcasting

In [36]:
list2

[3, 5, 6, 8, 10, 15]

In [39]:
for i in list2:
    print(i + 5)

8
10
11
13
15
20


In [40]:
arr1

array([1, 3, 5, 7, 4, 6])

In [44]:
#broadcasting
arr1 * 5

array([ 5, 15, 25, 35, 20, 30])

### Working with Mathematical Functions
Numpy provides a vast array of mathematical functions to perform operations on arrays.

In [ ]:
square root
mean
max
min
avg
ceil
log


In [46]:
arr1

array([1, 3, 5, 7, 4, 6])

In [45]:
np.max(arr1)

7

In [47]:
np.min(arr1)

1

In [48]:
np.average(arr1)

4.333333333333333

In [49]:
np.sum(arr1)

26

In [50]:
#this is done element-wise
np.sqrt(arr1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 2.        ,
       2.44948974])

In [51]:
np.square(arr1)

array([ 1,  9, 25, 49, 16, 36], dtype=int32)

In [53]:
np.exp(arr1)

array([   2.71828183,   20.08553692,  148.4131591 , 1096.63315843,
         54.59815003,  403.42879349])

In [54]:
np.log(arr2)

array([1.09861229, 1.60943791, 1.79175947, 2.07944154, 2.30258509,
       2.7080502 ])

In [ ]:
# Mathematical functions
np.sqrt(arr)
np.log(arr)


## Exploring Data with Pandas

Pandas is a library offering high-performance, easy-to-use data structures, and data analysis tools. The DataFrame is one of Pandas' most important classes.


### Creating a DataFrame
```python
import pandas as pd

data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Age': [28, 34, 29, 32]}
df = pd.DataFrame(data)
print(df)
```

In [59]:
import pandas as pd

In [ ]:
#you create a dataframe using a dictionary

In [62]:
data = {'Name': ['Lekan', 'Olaoluwa', 'Peter', 'Suliman'], 'Age': [20,35, 70, 90], 'Income':[5000, 7000, 8000, 6500]}

In [70]:
data

{'Name': ['Lekan', 'Olaoluwa', 'Peter', 'Suliman'],
 'Age': [20, 35, 70, 90],
 'Income': [5000, 7000, 8000, 6500]}

In [63]:
type(data)

dict

In [64]:
pd.DataFrame(data)

Name  Age  Income
0     Lekan   20    5000
1  Olaoluwa   35    7000
2     Peter   70    8000
3   Suliman   90    6500

In [65]:
#storing to a variable
df = pd.DataFrame(data)

In [66]:
df

Name  Age  Income
0     Lekan   20    5000
1  Olaoluwa   35    7000
2     Peter   70    8000
3   Suliman   90    6500


### Reading Data from Files
Pandas can easily read data stored in different file formats like CSV, Excel, or JSON.
```python
df = pd.read_csv('filename.csv')
```

In [ ]:
pd.read

In [71]:
df = pd.read_csv('Supermarket.csv')

In [77]:
df.head()

Product Identifier Supermarket Identifier Product Supermarket Identifer  \
0              NCA29            CHUKWUDI046             NCA29_CHUKWUDI046   
1              FDG53            CHUKWUDI049             FDG53_CHUKWUDI049   
2              NCN05            CHUKWUDI045             NCN05_CHUKWUDI045   
3              NCV17            CHUKWUDI046             NCV17_CHUKWUDI046   
4              FDK03            CHUKWUDI045             FDK03_CHUKWUDI045   

   Product Weight Product Fat Content  Product Shelf Visibility  \
0          10.500              Lo Fat                  0.027276   
1          10.000             Low Fat                  0.045928   
2           8.235              Lo Fat                  0.014489   
3          18.850             Low Fat                  0.016108   
4          12.600          Normal Fat                  0.074070   

         Product Type  Product Price Supermarket Opening Year  \
0           Household         428.28                     2004   
1        Frozen Foods         345.30                     2006   
2  Health and Hygiene         459.49                     2009   
3  Health and Hygiene         324.41                     2004   
4               Dairy         635.59                     2009   

  Supermarket  Size Supermarket Location Type   Supermarket Type  \
0             Small                 Cluster 1  Supermarket Type1   
1            Medium                 Cluster 1  Supermarket Type1   
2               NaN                 Cluster 2  Supermarket Type1   
3             Small                 Cluster 1  Supermarket Type1   
4               NaN                 Cluster 2  Supermarket Type1   

  Average Price per ProductType  Product Supermarket Sales  
0                    399.999418                    8983.31  
1                   388.0710941                    4893.63  
2                   367.1430293                    7323.80  
3                   367.1430293                    7541.85  
4                   409.5043429                   11445.10

In [78]:
df.tail()

Product Identifier Supermarket Identifier Product Supermarket Identifer  \
2989              FDK21            CHUKWUDI045             FDK21_CHUKWUDI045   
2990              NCJ05            CHUKWUDI049             NCJ05_CHUKWUDI049   
2991              FDI04            CHUKWUDI019             FDI04_CHUKWUDI019   
2992              DRG37            CHUKWUDI013             DRG37_CHUKWUDI013   
2993              FDE51            CHUKWUDI013             FDE51_CHUKWUDI013   

      Product Weight Product Fat Content  Product Shelf Visibility  \
2989           7.905             Low Fat                  0.010033   
2990          18.700             Low Fat                  0.046160   
2991             NaN          Normal Fat                  0.127660   
2992          16.200             Low Fat                  0.019362   
2993           5.925          Normal Fat                  0.096387   

            Product Type  Product Price Supermarket Opening Year  \
2989         Snack Foods         620.85                     2009   
2990  Health and Hygiene         380.92                     2006   
2991        Frozen Foods         496.36                     1992   
2992         Soft Drinks         386.74                     1994   
2993               Dairy         114.02                     1994   

     Supermarket  Size Supermarket Location Type   Supermarket Type  \
2989               NaN                 Cluster 2  Supermarket Type1   
2990            Medium                 Cluster 1  Supermarket Type1   
2991             small                 Cluster 1      Grocery Store   
2992              High                 Cluster 3  Supermarket Type1   
2993              High                 Cluster 3  Supermarket Type1   

     Average Price per ProductType  Product Supermarket Sales  
2989                     395.35219                    1877.56  
2990                   367.1430293                    4192.88  
2991                   388.0710941                    1977.43  
2992                   386.9982375                    4284.42  
2993                   409.5043429                     892.17

In [79]:
df.shape

(2994, 14)

In [87]:
#slicing
df[2:15]

Product Identifier Supermarket Identifier Product Supermarket Identifer  \
2               NCN05            CHUKWUDI045             NCN05_CHUKWUDI045   
3               NCV17            CHUKWUDI046             NCV17_CHUKWUDI046   
4               FDK03            CHUKWUDI045             FDK03_CHUKWUDI045   
5               FDV02            CHUKWUDI027             FDV02_CHUKWUDI027   
6               FDF17            CHUKWUDI017             FDF17_CHUKWUDI017   
7               FDA26            CHUKWUDI019             FDA26_CHUKWUDI019   
8               FDZ09            CHUKWUDI049             FDZ09_CHUKWUDI049   
9               FDL08            CHUKWUDI027             FDL08_CHUKWUDI027   
10              FDW20            CHUKWUDI010             FDW20_CHUKWUDI010   
11              FDX44            CHUKWUDI013             FDX44_CHUKWUDI013   
12              NCI29            CHUKWUDI017             NCI29_CHUKWUDI017   
13              FDZ10            CHUKWUDI013             FDZ10_CHUKWUDI013   
14              FDN44            CHUKWUDI017             FDN44_CHUKWUDI017   

    Product Weight Product Fat Content  Product Shelf Visibility  \
2            8.235              Lo Fat                  0.014489   
3           18.850             Low Fat                  0.016108   
4           12.600          Normal Fat                  0.074070   
5              NaN             Low Fat                  0.060252   
6            5.190             Low Fat                  0.042862   
7              NaN           Norml Fat                  0.129425   
8           17.600             Low Fat                  0.105042   
9              NaN              Lo Fat                  0.049478   
10          20.750             Low Fat                  0.040421   
11           9.300             Low Fat                  0.042931   
12           8.600             Low Fat                  0.032806   
13          17.850             Low Fat                  0.044426   
14          13.150       Ultra Low fat                  0.022925   

             Product Type  Product Price Supermarket Opening Year  \
2      Health and Hygiene         459.49                     2009   
3      Health and Hygiene         324.41                     2004   
4                   Dairy         635.59                     2009   
5                   Dairy         426.78                     1992   
6            Frozen Foods         492.03                     2014   
7                   Dairy         548.37                     1992   
8             Snack Foods         409.72                     s006   
9          Fruits and Veg         613.54                     1992   
10  Fruits and Vegetables         305.43                     2005   
11  Fruits and Vegetables         221.29                     1994   
12     Health and Hygiene         359.04                     2014   
13            Snack Foods         312.26                     1994   
14         Fruits and Veg         394.73                     2014   

   Supermarket  Size Supermarket Location Type   Supermarket Type  \
2                NaN                 Cluster 2  Supermarket Type1   
3              Small                 Cluster 1  Supermarket Type1   
4                NaN                 Cluster 2  Supermarket Type1   
5             Medium                 Cluster 3  Supermarket Type3   
6                NaN                 Cluster 2  Supermarket Type1   
7              Small                 Cluster 1      Grocery Store   
8             Medium                 Cluster 1  Supermarket Type1   
9             Medium                 Cluster 3  Supermarket Type3   
10               NaN                 Cluster 3      Grocery Store   
11              High                 Cluster 3  Supermarket Type1   
12               NaN                 Cluster 2  Supermarket Type1   
13              High                 Cluster 3  Supermarket Type1   
14               NaN                 Cluster 2  Supermarket Type1   

   Average Price per Pr